### ISSUE TITLE
Website workflow run: build-website fails

### ISSUE THREAD

**Issue by cknuepfer** [carpentries/training-template#71]
On a generated [repository](https://github.com/zedif/2022-12-06-ttt-online) the job `build-website` of the workflow `Website` always fails with error message:

```
Unable to resolve action `r-lib/actions@master`, unable to find version `master`
```

This happens already in the section `Set up job`, directly after `Getting action download info`, see [log](https://github.com/zedif/2022-12-06-ttt-online/actions/runs/3319407058/jobs/5518809819).

The website is correctly deployed via `pages-build-deployment `. Btw, what is the workflow `Website` used for?

**Comment by zkamvar** [comment]
Thank you for opening this issue, @cknuepfer!

In short, the `Website` workflow is used to run automated checks for Carpentries websites and, if needed, render R Markdown files into Markdown. For your website, the failing workflow is benign, as you correctly identified that it still builds. 

This has previously been identified in https://github.com/carpentries/styles/issues/641, but this particular repository had slipped beyond my detection because I was focused on lessons.

I will update this repository today. Thank you again for the issue and feel free to either modify or delete that workflow as you see fit for your repo.
